import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProductsService {

  private localStorageKey = 'productList';

  constructor() { }

  getProducts(): string[] {
    const storedProducts = localStorage.getItem(this.localStorageKey);
    return storedProducts ? JSON.parse(storedProducts) : this.getDefaultProducts();
  }

  private getDefaultProducts(): string[] {
    return [
      'Ananas',
      'Arbuz',
      'Awokado',
      'Bakłażan',
      'Banany',
      'Banan zielony',
      'Bataty',
      'Bazylia',
      'Bazylia cięta',
      'Bób',
      'Boczniaki',
      'Borówki',
      'Botwina',
      'Bratki',
      'Brokuł',
      'Brzoskwinia',
      'Brzoskwinie',
      'Buraki',
      'Cebula',
      'Cebula czerwona',
      'Cebula zielona',
      'Cebulka zielona*',
      'Cherry',
      'Chilli',
      'Cytryna',
      'Cukinia',
      'Czereśnie',
      'Cykoria biała',
      'Cykoria czerwona',
      'Czosnek',
      'Czosnek obrany',
      'Daktyle',
      'Dynia',
      'Dynia hokaido',
      'Fasolka szparagowa zielona',
      'Fasolka szparagowa żółta',
      'Figi',
      'Granat',
      'Grapefruit',
      'Grapefruit biały',
      'Gruszki',
      'Grzyby suszone',
      'Groszek cukrowy',
      'Jagoda',
      'Jabłka drobne',
      'Jabłka grube',
      'Jajka',
      'Jarmuż',
      'Jarzynka',
      'Jeżyny',
      'Kabaczek',
      'Kabocha',
      'Kalafior',
      'Kalarepa',
      'Kap kisz wor',
      'Kapusta biała',
      'Kapusta czerwona',
      'Kapusta kisz',
      'Karambola',
      'Kiełki',
      'Kiełki brokuła',
      'Kiełki groszku',
      'Kiełki lucerny',
      'Kiełki rzodkiewki',
      'Kiełki słonecznika',
      'Kiwi',
      'Koper',
      'Koper włoski',
      'Kwiatki',
      'Lima',
      'Limonka',
      'Lubczyk',
      'Maliny',
      'Mandarynka',
      'Mango',
      'Marakuja',
      'Marchew',
      'Marchew młoda',
      'Marchewki kolorowe',
      'Melony',
      'Mięta',
      'Mięta cięta',
      'Morela',
      'Morele suszone',
      'Natka',
      'Natka dekoracyjna',
      'Nektarynka',
      'Ogórek kisz',
      'Ogórek kisz wor',
      'Ogórki',
      'Ogórki gruntowe',
      'Ogórki małosolne',
      'Papryka czerwona',
      'Papryka zielona',
      'Papryka żółta',
      'Pakczoj',
      'Pasternak',
      'Peperoni',
      'Phisalis',
      'Pieczarka',
      'Pietruszka',
      'Pekin',
      'Pomarańcza',
      'Pomidory',
      'Pomidory malinowe',
      'Pomidor koktajlowy mix',
      'Por',
      'Porzeczki',
      'Roszponka',
      'Rozmaryn',
      'Rukola',
      'Rzepa biała',
      'Rzodkiewka',
      'Sałata',
      'Sałata dekoracyjna czerwona',
      'Sałata dekoracyjna zielona',
      'Sałata freeze',
      'Sałata lodowa',
      'Sałata mix',
      'Sałata rzymska',
      'Seler',
      'Seler naciowy',
      'Seler zielony',
      'Słonecznik',
      'Szczaw',
      'Szczawik krwisty',
      'Szczypiorek',
      'Śliwka suszona',
      'Śliwka wędzona',
      'Śliwka zachodnia',
      'Śliwki polskie duże',
      'Śliwki polskie małe',
      'Szparagi',
      'Szpinak',
      'Szpinak baby',
      'Tymianek',
      'Truskawki',
      'Winogrona czerwone',
      'Winogrona zielone',
      'Ziemniaki'
    ];
  }
}
